Add option to set bg to hard_black for gui.
srcery-colors/srcery-vim pull request #104
Opened 2023-09-04 14:09 UTC by micangl

Srcery already has a vim-only option to set the terminal background to hard_black. This commit adds another option, g:srcery_hard_black_gui_bg, compatible with the termguicolors (both Vim and Neovim) set-option.

2023-09-04 14:13 UTC, micangl commented
This was already partially possible by modifying the value of `g:srcery_black` in one's own config. Needless to say, this is all but an elegant solution.

2023-09-05 11:14 UTC, roosta commented
This looks good, but I was a bit confused by the option name, `gui` makes me think of gvim, not the background. How about naming the option `srcery_high_contrast_bg`? Possibly we should rename option `srcery_hard_black_terminal_bg` to `srcery_high_contrast_terminal_bg` What do you think @MindTooth ?

2023-09-05 11:17 UTC, roosta commented
We should probably mention in the readme that these options are exclusive, so bg passthrough wont work if you set this option, and vice versa.

2023-09-05 11:33 UTC, MindTooth commented
Would it be better that the background could take a value instead?  Instead of having two variables controlling the same thing. 🤷🏻‍♂️   Might be that I'm missing something, but are they the same?

2023-09-05 11:39 UTC, roosta commented
Agree, that would be better. The way it is now is confusing, and cause issues if you have more than one background option set.

We could allow a custom background value, and default to regular black.

2023-09-05 12:14 UTC, micangl commented
Having the option take a specific RGB value would definitely be an improvement.

2023-09-05 16:19 UTC, micangl commented
I've noticed that I was wrong in the last message. It's possible to remove the `g:srcery_hard_black_terminal_bg` option, since the highlight function takes as the `guibg` argument a list of of two elements: `[<gui_background>, <cterm_background>].
In the last commit I've set the <cterm_background> to 0, since I didn't know how you'd like the user to be able to customize the color. What I mean, by this, is: What option should we give the user to let him customize the gui and cterm bg colors?
A possible option would be to make the `g:srcery_bg` variable a list, which could then be passed directly to the highlight function: `let g:srcery_bg = [<guibg>, <ctermbg>]. A drawback is that the user would have to configure manually both the gui and cterm values, even if he were to be only interested in one.
The only other option I can think of is to have two variables, each with a default value (so that the user could only set the one he's interested in), and then combine them in a list (maybe, by defining a global varible containing the list, or directly passing the variable in a list to the highlight function).

2023-09-07 11:34 UTC, roosta commented
Sorry about the delay on this, I've been swamped with projects and not had time to look at this yet. I'll have to test this branch a bit, not sure about the best approach yet. Is it possible to set the background to `none` in your current configuration?

2023-09-08 11:14 UTC, micangl commented
> Is it possible to set the background to none in your current configuration?
Isn't that what the g:srcery_bg_passthrough option is for?

2023-09-08 12:26 UTC, roosta commented
yes, but the idea was to combine all the background options into a single var, instead of having mutually exclusive options.

2023-09-09 09:07 UTC, micangl commented
We could try something like this inside `autoload/srcery.vim`:
```
if !exists('g:srcery_bg')
  "Sets default for both guisp and cterm backgrounds.
  let g:srcery_bg=[g:srcery_black, 0]
elseif index(g:srcery_bg, 'DEFAULT') >= 0
  if g:srcery_bg[0] == 'DEFAULT'
    let g:srcery_bg[0] = g:srcery_black
  endif
  if g:srcery_bg[1] == 'DEFAULT'
    let g:srcery_bg[1] = 0
  endif
endif
```
If the user wants to set the background as `none`, he can simply specify 'NONE', as this is what Srcery internally uses.

2023-09-15 12:04 UTC, roosta commented
yeah, something like that could work. Feel free to push more commits, if you got a working implementation. I'm thinking that the terminal background remains a separate option cause I can imagine someone wanting a different background for only that.

2023-09-15 12:23 UTC, micangl commented
>I'm thinking that the terminal background remains a separate option cause I can imagine someone wanting a different background for only that.<
What do you mean exactly by this?

2023-09-15 12:47 UTC, roosta commented
Just that I'd like that to remain a separate option, looks like it is right now, viewing a8842ea. Just forget I mentioned it :)

2023-09-16 00:19 UTC, micangl commented
I haven't updated the documentation yet. To specify the background colors, add the following line to your config:
```
 let g:srcery_bg = [<guibg>, <ctermbg>]
```
To leave one of the two to the default value set it to `'DEFAULT'`. To set it to s:none, use `'NONE'`.

2023-09-23 11:24 UTC, roosta requested changes
I apologize for the slow response time on this, I've not had a chance to test out thoroughly until now, and everything seems to be working very well, I wasn't able to find any issues except for a few nitpicks pointed out in this review

2023-09-23 11:24 UTC, roosta commented on autoload/srcery.vim
> +    if g:srcery_bg[i] == 'DEFAULT' || (g:srcery_bg[i] == 'NONE' && has('gui_running'))
```suggestion
    if g:srcery_bg[i] ==# 'DEFAULT' || (g:srcery_bg[i] ==# 'NONE' && has('gui_running'))
```

2023-09-23 11:24 UTC, roosta commented on colors/srcery.vim
> -
I'd like this added back

2023-09-23 16:33 UTC, merged

2023-09-23 16:34 UTC, roosta commented
Thank you for your contribution! Appreciate your willingness to modify the PR, and I'm happy with the new option, gives more flexibility.

2023-09-23 16:39 UTC, micangl commented
No problem. I still need to update the documentation, though. Will it during next week.